spring:
  application.name: video_storage_backend

  jpa:
    hibernate.ddl-auto: none

video:
  folderPath: ${VIDEO_FOLDER_PATH:/videos} #Sciezka wzieta ze zmiennej srodowiskowej lub jezeli jej nie ma domyslna wartosc /videos